# Generated by Django 5.2.3 on 2025-07-11 09:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_name', models.CharField(max_length=100)),
                ('preference_value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text="List of selected values for this preference (e.g., ['blue', 'green'])", size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORS.user')),
            ],
            options={
                'unique_together': {('user', 'preference_name')},
            },
        ),
    ]
