# Generated by Django 5.2.3 on 2025-07-15 06:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssentialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('onepiece', 'Dresses/Jumpsuits'), ('bags', 'Bags/Backpacks'), ('sets', 'Co-ords/Suits/Sets')], max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='essentials/')),
                ('season_suitability', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('occasion_suitability', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('style_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('pattern', models.CharField(blank=True, choices=[('solid', 'Solid'), ('striped', 'Striped'), ('floral', 'Floral'), ('plaid', 'Plaid'), ('other', 'Other')], max_length=20, null=True)),
                ('fabric_density', models.CharField(blank=True, choices=[('lightweight', 'Lightweight'), ('medium', 'Medium'), ('heavy', 'Heavy')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('onepiece', 'Dresses/Jumpsuits'), ('bags', 'Bags/Backpacks'), ('sets', 'Co-ords/Suits/Sets')], max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wardrobe_images/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_basic_essential', models.BooleanField(default=False)),
                ('season_suitability', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="e.g., ['Summer', 'Spring']", size=None)),
                ('occasion_suitability', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="e.g., ['Casual', 'Work']", size=None)),
                ('style_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text="e.g., ['Bohemian', 'Minimalist']", size=None)),
                ('pattern', models.CharField(blank=True, choices=[('solid', 'Solid'), ('striped', 'Striped'), ('floral', 'Floral'), ('plaid', 'Plaid'), ('other', 'Other')], max_length=20, null=True)),
                ('fabric_density', models.CharField(blank=True, choices=[('lightweight', 'Lightweight'), ('medium', 'Medium'), ('heavy', 'Heavy')], max_length=20, null=True)),
                ('last_worn_date', models.DateTimeField(blank=True, null=True)),
                ('essential_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORS.essentialitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
