# Generated by Django 5.2.3 on 2025-07-15 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0002_essentialitem_wardrobeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='essentialitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ORS.essentialitem'),
        ),
    ]
