# Generated by Django 5.2.3 on 2025-07-17 06:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0003_essentialitem_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=100)),
                ('preferred_styles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('color_themes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None)),
                ('user_prompt', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('weather_condition', models.CharField(max_length=50)),
                ('conceptual_gen_ai_prompt_sent', models.TextField()),
                ('conceptual_gen_ai_description', models.TextField()),
                ('refined_gen_ai_prompt_sent', models.TextField()),
                ('gen_ai_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_items', models.ManyToManyField(to='ORS.wardrobeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
