# Generated by Django 5.2.3 on 2025-07-25 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0004_outfitrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitrecommendation',
            name='final_outfit',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GeneratedOutfitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('prompt_used', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='ORS.outfitrecommendation')),
            ],
        ),
        migrations.AddField(
            model_name='outfitrecommendation',
            name='outfit_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_recommendation', to='ORS.generatedoutfitimage'),
        ),
    ]
